spring:
  application:
    name: lanrenspace.edu.service.resume
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(5CZkguuFOGXheF+G2rIChM7XVkBXSISZTTFy0JYJbk5mQw0lm813f+3gwIW6DAA240mIn2TCzX/Or4rAy2Wg5m3+BzSZj4VUx/oacyCAbrMKkwcjIb++/zYMcngm9T8J)
    username: ENC(4HgajeSS0RdXSoh6sHT2Pg==)
    password: ENC(/b/ZHuDCm0r/p5O3NlpR3g==)
    jpa:
      database: MySQL
      show-sql: true
#注册到Eureka服务中心
edu:
  eureka: LanrenspaceEduEurekaServerNodeA
eureka:
  client:
    service-url:
      #defaultZone: http://${edu.eureka}:8761/eureka,http://${edu.eureka}:8762/eureka,http://${edu.eureka}:8763/eureka
      defaultZone: http://${edu.eureka}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
